public enum ProductionType
{
    None = 0,
    Ap,
    Gold,
    TaleStone,
    DungeonTicket,
    TotalWarTicket,
    MemoryCoin,
    ExpeditionCoin,
    TotalWar_01,
    ArcanaCoin,
    ArenaCoin,
    ArenaTicket,
    PracticeBookTicket,
    Item_Ticket_GachaTicket,
    Item_Ticket_TenRoll_GachaTicket,
    Item_GachaTicket_3GradeFix_TenRoll,
    Item_GachaTicket_RedFix_TenRoll,
    Item_GachaTicket_BlueFix_TenRoll,
    Item_GachaTicket_GreenFix_TenRoll,
    Item_GachaTicket_GuardianKnightFix_TenRoll,
    Item_GachaTicket_MageShooterFix_TenRoll,

    // EVENT
    Item_Coin_EventAdventure_Flask,
    Item_Coin_EventAdventure_FlagPen,
    Item_EventAdventure_BossTicket,
    Item_Coin_Event_ApBoost_HeroGrowthBoost,
    Item_Coin_Event_TileBreak_Halloween2025,
    Item_Coin_EventAdventure_N002OceanSpa_Soap,
    Item_Coin_EventAdventure_N002OceanSpa_Egg,
    Item_Coin_EventAdventure_N002OceanSpa_Towel,
    Item_Coin_EventAdventure_N002OceanSpa_Basket,
    Item_Coin_GuideMissionStackClear_Hotspring,
    Item_EventAdventure_N002OceanSpa_BossTicket,
    Item_Coin_ChallengeMission_XMas2025,
    Max,
};